bump_version: null
lint:
  files_exist:
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - conf/igenomes.config
  - conf/igenomes_ignored.config
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Nadja Nolte
  description: This is a nextflow pipeline for the analysis of allele-specific expression
    in polyploid plants using long-read RNA-seq.
  force: true
  is_nfcore: true
  name: plantlongrnaseq
  org: nf-core
  outdir: .
  skip_features:
  - igenomes
  version: 1.0.0dev
update: null
